### ISSUE TITLE
prerender-demo 预渲染，加载数据失败

### ISSUE THREAD

**Issue by Yadea-Web** [alowkeyguy/zgtBlog#1]
你好，我使用prerender-demo，打包出来的没有网络请求数据。我把网络请求写成一个延时执行，打包出来依旧没有改变。现在不知道是什么问题，你可以看下你的Demo还正常吗？谢谢

**Comment by alowkeyguy** [comment]
rap凉了，所以那个接口没法正常访问了。你自己用node写个接口试试，应该可以的。

**Comment by alowkeyguy** [comment]
> 你好，我使用prerender-demo，打包出来的没有网络请求数据。我把网络请求写成一个延时执行，打包出来依旧没有改变。现在不知道是什么问题，你可以看下你的Demo还正常吗？谢谢

rap凉了，所以那个接口没法正常访问了。你自己用node写个接口试试，应该可以的。
